apiVersion: v1
kind: Service
metadata:
  namespace: stonecap
  labels:
    app: traefik
  name: traefik
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "tls"
      port: 443
      targetPort: 443
  selector:
    app: traefik