kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc-traefik
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - eu-west-2b