apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: production-postgres-data
  namespace: $K8_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-postgres
  resources:
    requests:
      storage: 100Mi