apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stonecap
  name: envs-production-django
data:
  DJANGO_ACCOUNT_ALLOW_REGISTRATION: "True"
  DJANGO_ADMIN_URL:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_AWS_ACCESS_KEY_ID:
  DJANGO_AWS_REGION: eu-west-2
  DJANGO_AWS_SECRET_ACCESS_KEY:
  DJANGO_AWS_STORAGE_BUCKET_NAME:
  DJANGO_SECRET_KEY:
  DJANGO_SECURE_SSL_REDIRECT: "False"
  DJANGO_SERVER_EMAIL:
  DJANGO_SETTINGS_MODULE: config.settings.production
  REDIS_URL: redis://redis:6379/0
  WEB_CONCURRENCY: "4"
  S3_BUCKET_NAME:
