apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: production-postgres-backups
  namespace: stonecap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-postgres
  resources:
    requests:
      storage: 100Mi