apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-claim
  namespace: stonecap
spec:
  storageClassName: ebs-sc-traefik
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi