apiVersion: v1
kind: ConfigMap
metadata:
  namespace: capstone
  name: envs-production-postgres
data:
  POSTGRES_DB: recondb
  POSTGRES_HOST: database.cxcocxzo1nap.eu-west-2.rds.amazonaws.com
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres