apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: production-postgres-data-backups
  namespace: capstone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 100Mi