apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-claim
  namespace: capstone
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi